Upgrade to raw-window-handle version 0.5
RustAudio/baseview pull request #134
Opened 2022-11-23 22:19 UTC by greatest-ape

2022-11-26 12:08 UTC, robbert-vdh requested changes

2022-11-26 12:08 UTC, robbert-vdh commented on src/x11/window.rs
>          handle.window = self.window_id as c_ulong;
The window's visual is missing here: https://github.com/rust-windowing/raw-window-handle/pull/83

2022-11-26 13:51 UTC, greatest-ape commented on src/gl/x11.rs
> +        let display = display as *mut xlib::_XDisplay;
Fixed

2022-11-26 13:56 UTC, greatest-ape commented on src/x11/window.rs
>          handle.window = self.window_id as c_ulong;
Fixed, provided that the https://docs.rs/xcb/0.9.0/xcb/xproto/type.Visualid.html used to create the window is indeed what is expected

2023-09-30 15:06 UTC, robbert-vdh commented
Rebased against the current master branch: https://github.com/robbert-vdh/baseview/tree/raw-window-handle-0.5 (in case anyone else needs it, or someone wants to merge this PR)

2023-10-07 13:11 UTC, robbert-vdh commented
Thanks for the PR! I rebased this on top of the latest master branch. ([diff](https://github.com/RustAudio/baseview/compare/cfb2b091120c2a7d31628802c9e76b39b5c103a1..0df43486ba43c53bb4e69775f35ef3f1569640b0)) There are still a bunch of old unmerged PRs, so I'm going through those now so we can reduce the backlog somewhat.

2023-10-07 13:12 UTC, merged