[WIP] Support resizing windows after creation
RustAudio/baseview pull request #136
Opened 2022-11-30 19:08 UTC by robbert-vdh

I've implemented this for Linux back in March, and I only just added Windows support. Still need to add macOS support, but I thought I'd submit a draft PR already because the changes needed for Windows support are pretty invasive. So we may want to discuss the best course of action first.

Resizing the window sends a `WM_SIZE` event and a couple other events to the window, so the window procedure and `WindowState` had to be changed to use interior mutability everywhere instead of wrapping the entire struct in a `RefCell`. This resolves most of the reentrant event call concerns from #130, but I'm not sure if it also prevents panics in that specific example  To make this work there's now a `deferred_tasks` queue for handling tasks that are the result of a call to one of the `Window` methods in an event handler that may also indirectly emit other events. Perhaps `Window::close()` should also be implemented this way.

The Linux implementation was extremely straightforward, and I'll get to the macOS one next.

This closes #121.

2022-12-01 17:33 UTC, robbert-vdh commented
So one thing I noticed is that the behavior for window resize notifications is different between the different platforms. On Windows the window handler would receive an event after the resize had successfully taken place, and on Linux this didn't happen. I changed the Linux implementation so it also does that. 

On Windows and macOS the implementations also sent you duplicate `Event::Window(WindowEvent::Resized(window_info))` events even if the new size is the same as the old one, so I changed the behaviors there to also only send the event if something changed.

2022-12-01 20:45 UTC, robbert-vdh commented
So the Linux and Windows versions work great. The macOS version doesn't seem to resize the view at all (standalone windows are still resized, but the contents don't resize). Apple's docs on this are extremely sparse, so if anyone with more experience programming for their platform would like to chime in I'd appreciate it a lot!

2022-12-02 19:19 UTC, robbert-vdh commented
Okay, everything _should_ work great now. I'd appreciate it if others could give this a try as well! I've implemented support for this in my [vizia fork](https://github.com/robbert-vdh/vizia) which is used by [`nih_plug_vizia`](https://github.com/robbert-vdh/nih-plug/). All plugins in that repo that use Vizia will support resizing and you can also try running `cargo run -p gain_gui_vizia --release`.

2022-12-02 21:24 UTC, robbert-vdh commented
Oh and something I have not yet done in this PR but that might improve perceived responsiveness is to draw a new frame as soon as the window resize event is received. Right now the `.on_frame()` call lags a bit behind the resize.

2022-12-06 04:14 UTC, glowcoil requested changes

2022-12-06 04:14 UTC, glowcoil commented on src/macos/window.rs
> +            let frame = unsafe { NSWindow::frameRectForContentRect_(ns_window, frame) };
This seems slightly incorrect — we're getting the frame rect, then setting its size to the content rect size, then converting it from content rect to frame rect. I think there should be a `contentRectForFrameRect:` call before setting the size.

I haven't tested this, but it seems possible for this code to end up moving the window position by the amount that the content rect is offset from the frame rect.

2022-12-16 22:22 UTC, robbert-vdh commented on src/macos/window.rs
> +            let frame = unsafe { NSWindow::frameRectForContentRect_(ns_window, frame) };
Sorry, somehow I saw your response and then promptly forgot about it until now! This does behave correctly in both embedded and standalone situations (and I saw this approach in multiple posts on Stack Overflow), but after looking at the `NSWindow` documentation for the seventh time I finally spotted a [`setContentSize`](https://developer.apple.com/documentation/appkit/nswindow/1419100-setcontentsize) which should do exactly what we want.

I tested 512c3f2393d606f91963773c73cbf3ab8de5eb57 with both NIH-plug+VIZIA and with a quick modification to the standalone that resizes when a certain key is pressed and both versions behave the same.

2022-12-30 00:45 UTC, glowcoil requested changes

2022-12-30 00:45 UTC, glowcoil commented on src/win/window.rs
> +    is_open: Rc<AtomicBool>,
Can we make this flag a `Cell<bool>` instead of an `AtomicBool`?

2022-12-30 00:45 UTC, glowcoil commented on src/win/window.rs
> +    deferred_tasks: Rc<RefCell<VecDeque<WindowTask>>>,
An alternate design here would be to store the `WindowHandler` in an `Option`, so that `Window` can just hold a direct reference to `WindowState` itself even during the build closure when the handler doesn't exist yet. That way `deferred_tasks` wouldn't need to be in an `Rc`. But I don't think that's an obvious improvement at this point (though it will probably be cleaner once `Window` accumulates more fields), so it's up to you if you want to keep it as is.

2022-12-30 01:09 UTC, glowcoil requested changes

2022-12-30 01:09 UTC, glowcoil commented on src/win/window.rs
> +                    SetWindowPos(
I think we need to call `AdjustWindowRectEx` here, like in `open` and `WM_DPICHANGED`.

2023-01-01 21:46 UTC, robbert-vdh commented on src/win/window.rs
> +    deferred_tasks: Rc<RefCell<VecDeque<WindowTask>>>,
And then wrap the entire `WindowState` in an `Rc` intead of a `Box`? The `WindowState` creates the `Window`.

2023-01-01 22:13 UTC, glowcoil requested changes

2023-01-01 22:13 UTC, glowcoil commented on src/win/window.rs
> -                let window_state = Box::from_raw(window_state_ptr);
Without the `from_raw` call, the window state will result in a leak.

2023-01-01 22:15 UTC, robbert-vdh commented on src/win/window.rs
> -                let window_state = Box::from_raw(window_state_ptr);
That was fixed in c10ca6b40f369b0f06921024fecdd5e33d9fe514.

2023-01-01 22:16 UTC, robbert-vdh commented on src/win/window.rs
> +    is_open: Rc<AtomicBool>,
Done.

2023-01-01 22:25 UTC, glowcoil commented on src/win/window.rs
> +    deferred_tasks: Rc<RefCell<VecDeque<WindowTask>>>,
An `Rc` wouldn't be necessary. `Window` only exists on the stack for the duration of the build closure and event handlers, and is only passed by reference to client code, so it could safely hold an actual reference to `WindowState` (as long as care is taken when the `WindowState` is actually freed). It would involve adding a lifetime to `platform::Window`, but the public `Window` struct does already have a lifetime parameter: https://github.com/RustAudio/baseview/blob/ee156fb8840452984b5f9946635e9a35b2857c41/src/window.rs#L55

Anyway, like I said, this is just an alternate possible design, so feel free to disregard it.

2023-01-01 22:28 UTC, robbert-vdh commented on src/win/window.rs
> +    deferred_tasks: Rc<RefCell<VecDeque<WindowTask>>>,
Oh, I thought `Window` didn't already had a lifetime bound. That's why I thought using an `Rc` was necessary here. I've already rewritten everything using `Rc`s but I'll change that to Box+immutable references again because juggling `Rc`s in the window proc so you can clone them is kind of nasty.

2023-01-01 22:44 UTC, robbert-vdh commented on src/win/window.rs
> +    deferred_tasks: Rc<RefCell<VecDeque<WindowTask>>>,
I made the change. I already did something like this before I reverted it because I didn't like all the added conditional logic for the lifetime parameters on `Window`, but this does scale better than threading through the individual fields.

2023-01-01 22:45 UTC, robbert-vdh commented on src/win/window.rs
> +                    SetWindowPos(
Good catch! Added it in 2d1c54263913ba447bd92e2d455f7231ab7cfbd8.

2023-01-01 23:05 UTC, glowcoil commented on src/win/window.rs
> +    deferred_tasks: Rc<RefCell<VecDeque<WindowTask>>>,
We could add the lifetime to all platforms' `Window` types and use `PhantomData` where necessary, but that might not be any better. Anyway, looks good to me!

2023-01-01 23:08 UTC, glowcoil commented on src/win/window.rs
> +                    SetWindowPos(
I think we should be passing `rect.right - rect.left` etc. to `SetWindowPos`; otherwise looks good!

2023-01-01 23:09 UTC, robbert-vdh commented on src/win/window.rs
> +                    SetWindowPos(
Ah yeah was just mindlessly refactoring things. Done.

2023-01-01 23:16 UTC, glowcoil approved these changes

2023-01-01 23:18 UTC, merged

2023-04-16 07:02 UTC, helgoboss commented
@robbert-vdh Thanks, the `deferred_tasks` queue is a good way to prevent the issue mentioned in #130, I just tested it! There's one small additional thing necessary to fix the issue: An API to let baseview consumers defer tasks, because the code in #130 which has reentrancy issues is not a part of the baseview crate itself. It's part of `egui-baseview`. I will make a PR.