Add logic for CursorEntered/CursorLeft on Windows
RustAudio/baseview pull request #150
Opened 2023-10-02 01:01 UTC by Fredemus

Necessary to fix https://github.com/vizia/vizia/issues/407, which is a bug that locks up the GUI when you press down on a mouse button inside the window and release the button outside the window.

2023-10-07 13:48 UTC, robbert-vdh requested changes
I think this can be implemented without any additional state tracking or heuristics.

Take a look at the documentation of [`TrackMouseEvent`](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-trackmouseevent). You can use it to get [`WM_MOUSEHOVER`](https://learn.microsoft.com/en-us/windows/desktop/inputdev/wm-mousehover) events when the cursor enters the client area, and [`WM_MOUSELEAVE`](https://learn.microsoft.com/en-us/windows/desktop/inputdev/wm-mouseleave) events when the cursor leaves the client area. You need to set both the `TME_HOVER` and the `TME_LEAVE` flags in the `TRACKMOUSEEVENT` struct for that to work, and you need to repeat the call any time you receiver either of the two window messages. So the idea is that you call it after creating the window, and you then repeat the exact same call when handling those two window messages.

2023-10-07 14:27 UTC, Fredemus commented
I first tried to do it like that, but `WM_MOUSEHOVER` ends up firing every time the mouse moves inside the window. This way it only happens the first time the mouse enters the window, which lines up with how it works on x11.

2023-10-08 11:33 UTC, robbert-vdh commented
In that case you'd be able to just only set `TME_HOVER` when initially creating the window and when handling `WM_MOUSELEAVE`, and only set `TME_LEAVE` when handling `WM_MOUSEENTER`, no? If that works that sounds like a better solution than approximating it by tracking mouse moves.

2023-10-08 13:19 UTC, Fredemus commented
> `WM_MOUSEENTER`

For some reason there is no `WM_MOUSEENTER`, only `WM_MOUSEHOVER`

2023-10-08 13:19 UTC, robbert-vdh commented
Sorry yeah I meant `WM_MOUSEHOVER`.

2023-10-08 14:17 UTC, Fredemus commented
Ah okay.  For reasons I don't really understand just sending `TrackMouseEvent` with `TME_HOVER` in `WM_MOUSELEAVE` means the event never fires, no matter if I set either `TME_HOVER` or `TME_LEAVE` initially, or both. I also tried to change `dwHoverTime` in case the system default was weird. It seemingly has to happen in `WM_MOUSEMOVE`. 

I digged up the [documentation I based this on](https://learn.microsoft.com/en-us/windows/win32/learnwin32/other-mouse-operations#mouse-tracking-events-hover-and-leave).

2023-10-09 21:09 UTC, robbert-vdh requested changes

2023-10-09 21:09 UTC, robbert-vdh commented on src/win/window.rs
> +                let track_mouse = Rc::new(TRACKMOUSEEVENT {
If there's no other way then I'd at least suggest removing this allocation. That is not needed.

2023-10-28 15:36 UTC, Fredemus commented on src/win/window.rs
> +                let track_mouse = Rc::new(TRACKMOUSEEVENT {
Sorry, somehow missed the notification. Fixed

2024-03-18 15:46 UTC, robbert-vdh approved these changes
I don't know how to feel about the Win32 API for this, but I guess this is the way to do it. :sweat_smile: 

LGTM.

2024-03-18 15:46 UTC, merged