add support for Window::Focused/Unfocused events on macOS
RustAudio/baseview pull request #171
Opened 2024-03-19 18:41 UTC by maxjvh

trigger `WindowEvent::Focused` and `WindowEvent::Unfocused` events when the plugin window gains/loses focus. implemented by adding observers to `NSNotificationCenter::defaultCenter()` that listen to `NSWindowDidBecomeKeyNotification` and `NSWindowDidResignKeyNotification` notifications on the `NSViews`' window.

tested and confirmed to work in Live, Bitwig, FL Studio, Reaper and AudioPluginHost.

2024-03-21 16:30 UTC, maxjvh commented
there was a slight oversight where the focus events were not sent correctly if the window contained other things besides just the NSView that houses the plugin. should be fixed now though, also added some comments for clarity.

2024-03-24 20:50 UTC, glowcoil requested changes

2024-03-24 20:50 UTC, glowcoil commented on src/macos/window.rs
> +    _observer: NSWindowNotificationObserver,
I don't think the `WindowHandle` is really the right place to store this. If the `WindowHandle` is dropped without closing the window, the window will stay open but we'll stop receiving focus events; and if the window is closed without dropping the `WindowHandle`, the observer will stay registered and we'll continue trying to deliver focus events (which I think will result in some use-after-frees in `handle_notification`).

2024-03-24 20:50 UTC, glowcoil commented on src/macos/window.rs
> +                let name = format!("BaseviewObserver_{}", Uuid::new_v4().to_simple());
This will leak a new class definition every time a new window is opened. To avoid this for our `NSView` subclass, we deregister the class definition in the [`dealloc` override](https://github.com/RustAudio/baseview/blob/26b019d6a278ac94d6011cebbfa13c8c9017306b/src/macos/view.rs#L229).

In fact, I think it should be possible to define the `handleNotification:` method directly on the `NSView` subclass and use that as the observer, similarly to how we use it as the `NSWindowDelegate` in [standalone mode](https://github.com/RustAudio/baseview/blob/26b019d6a278ac94d6011cebbfa13c8c9017306b/src/macos/window.rs#L241).

2024-03-24 20:50 UTC, glowcoil commented on src/macos/window.rs
> +            let window_state_ptr = Rc::into_raw(Rc::clone(&window_state));
This call to `Rc::into_raw` has no matching call to `Rc::from_raw`, which means that the `WindowState` will never get freed. You could fix this by adding cleanup code, but I think the suggestion above to use the `NSView` itself as the observer would also fix it in a simpler way.

2024-03-24 21:01 UTC, maxjvh commented on src/macos/window.rs
> +                let name = format!("BaseviewObserver_{}", Uuid::new_v4().to_simple());
using `NSView` as the observer is a great idea, thanks!

2024-03-24 21:44 UTC, maxjvh reviewed
thanks for the review @glowcoil! making NSView the observer seemed to address all your comments. just a few questions here still.

2024-03-24 21:44 UTC, maxjvh commented on src/macos/view.rs
> +        name:NSString::alloc(nil).init_str(notification_name)
this NSString gets automatically released i assume?

2024-03-24 21:44 UTC, maxjvh commented on src/macos/view.rs
> +        let () = msg_send![notification_center, removeObserver:this];
would feel better to remove the observer before calling dealloc on the superclass, but apparently the call moves `this` and couldn't figure out how to do it otherwise

2024-03-24 21:44 UTC, maxjvh commented on src/macos/view.rs
> +        if notification_object == window && first_responder == state.window_inner.ns_view {
how to compare `first_responder: id` with `this: &Object`? would make things even more clean and make the only change in window.rs unnecessary

2024-03-24 23:09 UTC, glowcoil commented on src/macos/view.rs
> +        let () = msg_send![notification_center, removeObserver:this];
I think the solution to this immediate problem would be to explicitly reborrow `this`, i.e. to pass `&*this` instead of `this` to `removeObserver:`. That should let you move this before the `[super dealloc]`.

However, I think it might be a better idea to just move this call out of `dealloc` and into `WindowInner::close`.

2024-03-24 23:20 UTC, glowcoil commented on src/macos/view.rs
> +        name:NSString::alloc(nil).init_str(notification_name)
I don't think it does, but you should be able to just call `autorelease` on it.

I think a nicer solution would be to statically link in the necessary string constants (warning, I haven't tested this):

```rust
#[link(name = "AppKit", kind = "framework")]
extern "C" {
    static NSWindowDidBecomeKeyNotification: id;
    static NSWindowDidResignKeyNotification: id;
}```

2024-03-24 23:21 UTC, glowcoil commented on src/macos/view.rs
> +        if notification_object == window && first_responder == state.window_inner.ns_view {
It should just work to cast `this as id`.

2024-03-25 07:05 UTC, maxjvh commented on src/macos/view.rs
> +        name:NSString::alloc(nil).init_str(notification_name)
this does work indeed! :)

2024-03-25 07:08 UTC, maxjvh commented on src/macos/view.rs
> +        if notification_object == window && first_responder == state.window_inner.ns_view {
worked when going through a const pointer first `this as *const Object as id`

2024-03-25 16:25 UTC, glowcoil approved these changes

2024-03-25 16:34 UTC, merged