Add additional CI checks
RustAudio/baseview pull request #182
Opened 2024-03-28 16:51 UTC by prokopyl

This PR adds a variety of checks to the CI:

* Check that all code and examples build without warnings using `-D warnings`. This is done for all platforms, with or without the OpenGL feature.
* Check that all documentation is valid, and that no documentation links are broken, using `cargo doc` with `-D warnings`.
* Run `clippy` with `-D warnings` (but otherwise only the default lints).
* Check formatting using `rustfmt`.

This PR also applies some light formatting and code fixes that were detected by `rustfmt` and `clippy`.

This also makes some updates to the actions used:
* Update `actions/checkout` to `v4`
* Replace `actions-rs/toolchain` (which is not maintained anymore) to `dtolnay/rust-toolchain` instead

Some further work that is not covered by this PR:
* The `missing-safety-doc` lint has been temporarily disabled. This will be re-enabled in another PR that will add the proper safety docs to the affected functions.
* `cargo-deny` has been discussed, but I prefer adding it in a later PR as it can be its own can of worms regarding licenses and dependencies.

2024-03-28 20:54 UTC, glowcoil requested changes

2024-03-28 20:54 UTC, glowcoil commented on .github/workflows/rust.yml
> +      run: cargo build --all --verbose
I think this should be `cargo build --workspace --all-targets`. `--all` is a deprecated alias for `--workspace` (see [here](https://doc.rust-lang.org/cargo/commands/cargo-build.html#package-selection)), which only specifies affects package selection, not target selection, so without `--examples` or `--all-targets`, the examples will no longer be built.

2024-03-29 03:11 UTC, prokopyl commented on .github/workflows/rust.yml
> +      run: cargo build --all --verbose
Ah, my bad, I thought it was the opposite. :sweat_smile:

2024-03-29 04:56 UTC, prokopyl commented on .github/workflows/rust.yml
> +      run: cargo build --all --verbose
Fixed now :slightly_smiling_face:

2024-03-29 05:03 UTC, glowcoil requested changes

2024-03-29 05:03 UTC, glowcoil commented on .github/workflows/rust.yml
> +      - run: cargo clippy --all --all-features -- -D warnings
I think `cargo clippy` will also take `--workspace --all-targets` :-)

2024-03-29 05:08 UTC, prokopyl commented on .github/workflows/rust.yml
> +      - run: cargo clippy --all --all-features -- -D warnings
Dangit lol, fixed now x)

2024-03-29 05:10 UTC, glowcoil approved these changes

2024-03-29 23:55 UTC, merged