Add and refactor events for iced integration
RustAudio/baseview pull request #40
Opened 2020-09-10 20:32 UTC by BillyDM

I set up the framework of events we should target on each platform if possible. I mostly followed the way `iced` structures its events.

2020-09-10 21:23 UTC, wrl requested changes

2020-09-10 21:23 UTC, wrl commented on src/lib.rs
> +    fn draw(&mut self, mouse_cursor: &mut MouseCursor);
why is passing the mouse cursor necessary here?

2020-09-10 21:23 UTC, wrl commented on src/macos/window.rs
> +                scale_factor: 1.0,
`scale` is fine.

2020-09-10 21:58 UTC, BillyDM commented on src/macos/window.rs
> +                scale_factor: 1.0,
Both iced an winit calls it `scale_factor`, but it's fine if you just want it to be `scale`.

2020-09-10 22:00 UTC, BillyDM commented on src/lib.rs
> +    fn draw(&mut self, mouse_cursor: &mut MouseCursor);
There needs to be a way to set the mouse cursor icon. In `iced` it is set after rendering, so I thought that we could implement it like that as well. Maybe it should be `fn draw(&mut self) -> Option<MouseCursor>` instead?

2020-09-10 22:04 UTC, wrl commented on src/macos/window.rs
> +                scale_factor: 1.0,
I don't think that the `_factor` adds any additional clarity or information and would indeed prefer we keep it `scale`.

2020-09-10 22:06 UTC, wrl commented on src/lib.rs
> +    fn draw(&mut self, mouse_cursor: &mut MouseCursor);
We're going to need more platform operations than just "set mouse cursor," so I don't think this is the right place to do it.

Also, I don't really think that `draw()` is the right place to be doing any of these sorts of operations anyway. They should happen in response to an event, so we'll need to pass some sort of a handle or struct into `on_event()` with operations like "open URL", "set cursor", "warp pointer", "open file selection dialog", etc.

I'm open to reading anything that shows why `iced` handles that in rendering but I don't think it's the right place to handle it.

2020-09-10 22:08 UTC, BillyDM commented on src/lib.rs
> +    fn draw(&mut self, mouse_cursor: &mut MouseCursor);
Do you think the return should be added to `on_event()` instead? We also need a way to tell `baseview` that the user wants to close the window. I'm thinking one of these methods should return a message struct.

2020-09-10 22:31 UTC, wrl commented on src/lib.rs
> +    fn draw(&mut self, mouse_cursor: &mut MouseCursor);
Returning operations means that only one event can happen in response, which isn't always a safe assumption. We need some object which is passed into `on_event()` which can have these operations called on it.

2020-09-10 22:45 UTC, BillyDM commented on src/lib.rs
> +    fn draw(&mut self, mouse_cursor: &mut MouseCursor);
Yeah, I figured. I'm working on a solution now!

2020-09-10 23:24 UTC, BillyDM commented
How do you feel about this design?

2020-09-10 23:41 UTC, BillyDM commented
Oh, hold on. There is one more thing I want to change.

2020-09-11 00:07 UTC, BillyDM commented
Okay, what do you think of this architecture?

2020-09-11 00:14 UTC, BillyDM commented
Do you like it this way, or do you think we should push requests onto a queue instead?

2020-09-11 00:31 UTC, wrl requested changes
I don't think that having a separate `WindowState` struct is going to solve the issue here.

What we need is to pass the `Window<A>` into the event handler the way that `WindowState` is being passed in now, and then the `Window<A>` needs `pub` functions for synchronously submitting these requests to the window system.

Whether that happens directly in the `impl<A> Window<A>` blocks and we have our types concrete or whether we have a platform-neutral `Window`/`WindowSystem`/`WindowHandle` type is something that @glowcoil and I disagree on (with @glowcoil being in the "concrete `impl` block" camp and me being in the "platform-neutral trait" camp).

2020-09-11 00:31 UTC, wrl commented on src/event.rs
> +}
Is there a reason this isn't just covered by the `Eq` auto-derive?

2020-09-11 00:31 UTC, wrl commented on src/event.rs
> +    ModifiersChanged(ModifiersState),
Will the window receive both a `ModifiersChanged` *and* the respective `KeyPressed`/`KeyReleased` events when a modifier is pressed/released?

2020-09-11 00:31 UTC, wrl commented on src/event.rs
> +    FilesHoveredLeft,
Any reason for the semantics here surrounding multiple files? Is this just how the iced abstractions work?

2020-09-11 00:31 UTC, wrl commented on src/event.rs
> +    Clipboard(Option<String>),
Let's not have event types here that we don't have implementations for already.

In particular, clipboard events are a bit of a minefield across platforms, and most platforms have more complex data models than simply strings (i.e. differing mime-types).

2020-09-11 00:31 UTC, wrl commented on src/window_state.rs
> +    }
No, unfortunately this is not going to work. We *need* to be able to make *synchronous* window system requests from inside the event handler.

When events/requests to/from the window system become buffered and asynchronous, that's when the frames of lag start piling up. We *cannot* buffer our most basic abstractions.

2020-09-11 00:33 UTC, BillyDM commented on src/event.rs
> +}
Oh, this is copy pasted from iced.

2020-09-11 00:34 UTC, BillyDM commented on src/event.rs
> +    FilesHoveredLeft,
Yeah, again copied from iced.

2020-09-11 00:34 UTC, BillyDM commented on src/window_state.rs
> +    }
Okay, I see.

2020-09-11 00:36 UTC, wrl commented on src/event.rs
> +    FilesHoveredLeft,
No worries! I don't intrinsically have a problem with splitting multiple files into independent events, just wanted to know where the semantics came from.

My preference would be to structure the events close to what the platforms themselves expose here, which, since it would entail a bottom-up design in the platform code, means that maybe let's hold off on the file events for now.

2020-09-11 00:36 UTC, BillyDM commented on src/event.rs
> +    ModifiersChanged(ModifiersState),
Oh yeah. Again iced is doing this.

2020-09-11 00:41 UTC, BillyDM commented on src/window_state.rs
> +    }
But if we poll for requests immediately after calling `self.app_window.on_event()`, then wouldn't that still be synchronous with the event handler?

2020-09-11 00:41 UTC, wrl commented on src/window_state.rs
> +    }
The issue is not necessarily in the *setter* operations that are currently implemented as long as those setters don't have to be called in a particular order, but for *getter* operations (such as "current clipboard contents" or "mouse double click interval", among others) it doesn't work at all unless we copy everything into this `WindowState` before dispatching events, which I don't think makes sense.

2020-09-11 00:42 UTC, wrl commented on src/window_state.rs
> +    }
> But if we poll for requests immediately after calling `self.app_window.on_event()` in the same function, then wouldn't that still be synchronous with the event handler?

For single setter calls, yes. Not always a safe assumption to make.

2020-09-11 00:54 UTC, BillyDM commented on src/window_state.rs
> +    }
Oh, yeah I see the issue now.

2020-09-11 01:15 UTC, glowcoil commented
> Whether that happens directly in the `impl<A> Window<A>` blocks and we have our types concrete or whether we have a platform-neutral `Window`/`WindowSystem`/`WindowHandle` type is something that @glowcoil and I disagree on (with @glowcoil being in the "concrete `impl` block" camp and me being in the "platform-neutral trait" camp).

TBH I'm open to either of these! I don't really have a strong preference.

2020-09-11 01:20 UTC, BillyDM commented
Okay, I'll work on a solution tomorrow!

2020-09-11 14:42 UTC, closed without merging