macOS: basic event handling
RustAudio/baseview pull request #52
Opened 2020-10-25 17:24 UTC by greatest-ape

Adds handling of mouse down events on macOS with a lot of code from https://github.com/antonok-edm/vst_window. The open_window example works.

Possible problems that I can think of:

- No reference to the created Window is stored in the WindowHandle, which means it can't be accessed later and cleanup must be handled by macOS (?).
- Parent window functionality has not been tested
- AsIfParented support is not implemented

If this looks like something we could make use of, I can have a look at implementing other events as well.

2020-10-25 23:17 UTC, greatest-ape commented
Several problems have been identified and fixed. Some remaining work to be done is:

- [ ] Get CursorMoved events when user is not dragging
- [ ] Test if parented views work
- [ ] Test if AsIfParented views work (AUv2 only)
- [ ] Accept keyboard events. Does acceptsFirstResponder or something similar need to be setup to accomplish this?
- [ ] Does the NSApp need to be created **before** setting up the non-parented window and get passed into the WindowHandle for _app_run_blocking_?

2020-10-26 01:32 UTC, wrl requested changes

2020-10-26 01:32 UTC, wrl commented on src/macos/window.rs
>              );
this `.clone()` here seems funky – do we need that?

2020-11-10 17:06 UTC, glowcoil commented on src/macos/window.rs
> +            ::std::ptr::null_mut
just as a style nit, I would prefer `.unwrap_or(::std::ptr::null_mut())`

2020-11-10 17:28 UTC, glowcoil commented on src/macos/window.rs
> +    pub(super) fn from_field(obj: &Object) -> &mut Self {
This function should be marked `unsafe`, since it is possible to create undefined behavior by calling it from purely safe code. The comment should just describe the requirements for calling it safely (not using it to create two simultaneous `&mut`s to the same WindowState).

2020-11-10 20:19 UTC, greatest-ape commented on src/macos/window.rs
> +    pub(super) fn from_field(obj: &Object) -> &mut Self {
Fixed

2020-11-10 20:21 UTC, greatest-ape commented on src/macos/window.rs
> +            ::std::ptr::null_mut
Fixed

2020-11-11 21:54 UTC, glowcoil approved these changes
Looks good to me! I tested and it works fine in both the parented and unparented cases.

2020-11-11 22:04 UTC, merged